# Site wide configuration

title:            ReputationVIP R&D
locale:           en_US
url:              http://reputationvip.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: ReputationVIP
  avatar: avatars/reputationvip.png
  bio: Welcome on ReputationVIP's tech place.<br />You will find on this blog technical articles, code samples, tutorials for beginners or advanced users about current methodologies and technologies. We will also share with you our feelings about how we organize ourselves to work in the best possible way as a team. Feel free to comment.
  email: #email
  web: http://www.reputationvip.com
  disqus-shortname: reputationvipio
  twitter: reputationvip
  facebook: reputationvip
  google:
    plus: reputationvip
    analytics: UA-26693719-5
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: ReputationVIP
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: reputation-vip
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

# Fork me on Github ribbon
forkme:
  active: true
  title: Fork me on Github
  url: https://github.com/ReputationVIP/reputationvip.github.io/fork
  # [ top-left, top-right, bottom-left, bottom-right ]
  position: top-right

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
